### ISSUE TITLE
[Question] Please suggest the way to build swagger doc within next case

### ISSUE THREAD

**Issue by denismakogon** [cr0hn/aiohttp-swagger#11]
Assume we have such wrapper on top of each route handler

```
def api_action(**outter_kwargs):
    """
    Wrapps API controller action actions handler
    :param outter_kwargs: API instance action key-value args
    :return: _api_handler

    Example:

    class Controller(ControllerBase):

        @api_action(method='GET')
        async def index(self, request, **kwargs):
            return web.Response(
                text=str(request),
                reason="dumb API",
                status=201)

    """

    def _api_handler(func):

        @functools.wraps(func)
        def wrapper(self, *args, **kwargs):
            return func(self, *args, *kwargs)

       # custom logic here
        return wrapper

    return _api_handler
```

So, coming from examples provided in README, we'd have next app

```
from aiohttp import web
from aiohttp_swagger import *

@api_action(method="GET", route="/ping")
async def ping(request):
    """
    ---
    description: This end-point allow to test that service is up.
    tags:
    - Health check
    produces:
    - text/plain
    responses:
        "200":
            description: successful operation. Return "pong" text
        "405":
            description: invalid HTTP Method
    """
    return web.Response(text="pong")


app = web.Application()

setup_swagger(app)

web.run_app(app, host="127.0.0.1")
```

eventually, swagger is not capable to be assembled (empty page). I tried to debug his problem and it appears that `route._handler.__doc__` is `None`, but if i would not use this decorator it will have the same doc string as `ping`. Can you please suggest me a way how to fix it?

**Comment by stasfilin** [comment]
@denismakogon Hi Denis,
you need add your route.

```python
from aiohttp import web
from aiohttp_swagger import *

async def ping(request):
    """
    ---
    description: This end-point allow to test that service is up.
    tags:
    - Health check
    produces:
    - text/plain
    responses:
        "200":
            description: successful operation. Return "pong" text
        "405":
            description: invalid HTTP Method
    """
    return web.Response(text="pong")


app = web.Application()
app.router.add_route('GET', "/ping", ping)

setup_swagger(app)

web.run_app(app, host="127.0.0.1")
```

**Comment by denismakogon** [comment]
@stasfilin, thanks for your replay, but i didn't include that piece of code here, so, it was added to an app, it means that it is not a source of a problem.

**Comment by denismakogon** [comment]
@stasfilin i was able to debug the problem, and it appears that problem is in aiohttp (cc @asvetlov).

Here's where [problem appears ](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L99-L121). The explanation is quite trivial, when coroutine is being decorated by regular function (which is not a coroutine), aiohttp just reassigns wrapper without pulling out required fields of decorated coroutine. So, [wrapper_handler](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L110) `__doc__` is obviously equals to `None`. And that's why aiohttp_swagger is not capable to pull out docstrings from route handlers.

In my own case, i would need to rewrite decorator to be a coroutine, but not a regular function.

**Comment by denismakogon** [comment]
So, fix to myself is trivial:

```
    def _api_handler(func):

        @functools.wraps(func)
        async def wrapper(self, *args, **kwargs):
            return await func(self, *args, *kwargs)

        # custom logic
        return wrapper
```

nested wrapper should also be a coroutine rather than a function. It is worth to have some explicit docs in aiohttp to address such cases.
