### ISSUE TITLE
Create sphinx docs

### ISSUE THREAD

**Issue by asvetlov** [cr0hn/aiohttp-swagger#4]
REAME is very good place for library introduction.

But sphinx documentation stored on readthedocs.io also makes sense.

The doc could contain not only introduction part but the reference for all public API.
For example I cannot figure out the full list of `setup_swagger` parameters without looking into the source code.

I believe you understand my pain very well.

**Comment by cr0hn** [comment]
Yeah, you're right. When I have some time I'll generate a real doc
