### ISSUE TITLE
Add _ prefix to private API.

### ISSUE THREAD

**Issue by asvetlov** [cr0hn/aiohttp-swagger#5]
I believe `swagger.swagger_home` etc. are not part or Public API.
Please rename the function to `swagger._swagger_home` and do the same for others.

It gives very clean vision for readers of your code: what is internal detail and what is a part of Public API.
Also it gives very obvious rule to you: **every** *name not started from _* should be documented and enlisted in module's `__all__`.

I know I don't always follow the recommendation myself, sorry.
But it is good advise, especially on very early stage as you have for the library now.

**Comment by cr0hn** [comment]
It's good idea. And I like good ideas :)
